//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOUV.Torp.Monitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOUV.Torp.Monitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本号 1.0.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string AppBarButton_Save {
            get {
                return ResourceManager.GetString("AppBarButton_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存结果.
        /// </summary>
        public static string AppBarButton_SaveResult {
            get {
                return ResourceManager.GetString("AppBarButton_SaveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1001.
        /// </summary>
        public static string Build_Number {
            get {
                return ResourceManager.GetString("Build_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 串口打开失败.
        /// </summary>
        public static string Comm_Failed {
            get {
                return ResourceManager.GetString("Comm_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 串口服务正常.
        /// </summary>
        public static string Comm_OK {
            get {
                return ResourceManager.GetString("Comm_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浮标水声通信平台参数.
        /// </summary>
        public static string GLOBALSETTING_Title_Top {
            get {
                return ResourceManager.GetString("GLOBALSETTING_Title_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浮标水声通信平台.
        /// </summary>
        public static string Home_Brand {
            get {
                return ResourceManager.GetString("Home_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水下航行器信息技术重点实验室.
        /// </summary>
        public static string Home_Brand_LOAT {
            get {
                return ResourceManager.GetString("Home_Brand_LOAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Laboratory of Information Technoloogy for AUVs,CAS.
        /// </summary>
        public static string Home_Brand_LOAT_E {
            get {
                return ResourceManager.GetString("Home_Brand_LOAT_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命令行模式.
        /// </summary>
        public static string Home_Tile_Console {
            get {
                return ResourceManager.GetString("Home_Tile_Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据分析.
        /// </summary>
        public static string Home_Tile_Data {
            get {
                return ResourceManager.GetString("Home_Tile_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实时通信.
        /// </summary>
        public static string Home_Tile_Live {
            get {
                return ResourceManager.GetString("Home_Tile_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基本设置.
        /// </summary>
        public static string Home_Tile_Setup {
            get {
                return ResourceManager.GetString("Home_Tile_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水声监控显控.
        /// </summary>
        public static string Home_Title_ApplicationName {
            get {
                return ResourceManager.GetString("Home_Title_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水声监控平台设置-实时监控.
        /// </summary>
        public static string Live_Title_Top {
            get {
                return ResourceManager.GetString("Live_Title_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水声监控系统程序.
        /// </summary>
        public static string Mon_ApplicationName {
            get {
                return ResourceManager.GetString("Mon_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水声监控系统正在运行.
        /// </summary>
        public static string Mon_RUNNING {
            get {
                return ResourceManager.GetString("Mon_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络未连接.
        /// </summary>
        public static string NETWORK_DOWN {
            get {
                return ResourceManager.GetString("NETWORK_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络连接出错！.
        /// </summary>
        public static string NETWORK_ERROR {
            get {
                return ResourceManager.GetString("NETWORK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络已连接.
        /// </summary>
        public static string NETWORK_OK {
            get {
                return ResourceManager.GetString("NETWORK_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水声监控系统.
        /// </summary>
        public static string SPLASH_BAND {
            get {
                return ResourceManager.GetString("SPLASH_BAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 多点浮标通信、位置呈现、目标监控.
        /// </summary>
        public static string SPLASH_BAND_DESCRIPTION {
            get {
                return ResourceManager.GetString("SPLASH_BAND_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水下航行器信息技术重点实验室.
        /// </summary>
        public static string SPLASH_COMPANY_NAME {
            get {
                return ResourceManager.GetString("SPLASH_COMPANY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  © 2017 中国科学院声学研究所 .
        /// </summary>
        public static string SPLASH_COPY_RIGHT {
            get {
                return ResourceManager.GetString("SPLASH_COPY_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浮标水声通信主控程序.
        /// </summary>
        public static string SPLASH_PRODUCT_NAME {
            get {
                return ResourceManager.GetString("SPLASH_PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版权所有.
        /// </summary>
        public static string SPLASH_RIGHT_RESERVER {
            get {
                return ResourceManager.GetString("SPLASH_RIGHT_RESERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.0.
        /// </summary>
        public static string SPLASH_VERSION {
            get {
                return ResourceManager.GetString("SPLASH_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        public static string Version_Number {
            get {
                return ResourceManager.GetString("Version_Number", resourceCulture);
            }
        }
    }
}
